"""Create the Databricks demo inputs from authoritative public sources.

The generated Parquet files are written under ``data/local`` and are ignored by
Git. Nothing downloaded or generated by this script should be committed.
"""

from __future__ import annotations

import argparse
import tempfile
from pathlib import Path
from urllib.request import urlretrieve

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq


TRIP_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2023-07.parquet"
ZONE_URL = "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv"
WEATHER_URL = "https://www.ncei.noaa.gov/oa/local-climatological-data/v2/access/2023/LCD_USW00094728_2023.csv"


def first_rows(source: Path, row_limit: int) -> pa.Table:
    parquet = pq.ParquetFile(source)
    batches: list[pa.Table] = []
    row_count = 0
    for row_group in range(parquet.num_row_groups):
        batch = parquet.read_row_group(row_group)
        batches.append(batch)
        row_count += batch.num_rows
        if row_count >= row_limit:
            break
    return pa.concat_tables(batches).slice(0, row_limit)


def prepare(output_dir: Path, row_limit: int) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="ride_hailing_sources_") as temporary:
        temporary_dir = Path(temporary)
        trip_source = temporary_dir / "fhvhv_tripdata_2023-07.parquet"
        zone_source = temporary_dir / "taxi_zone_lookup.csv"
        weather_source = temporary_dir / "weather_2023.csv"

        print("Downloading NYC TLC July 2023 HVFHV source...")
        urlretrieve(TRIP_URL, trip_source)
        print("Downloading NYC TLC taxi-zone lookup...")
        urlretrieve(ZONE_URL, zone_source)
        print("Downloading NOAA 2023 weather observations...")
        urlretrieve(WEATHER_URL, weather_source)

        pq.write_table(
            first_rows(trip_source, row_limit),
            output_dir / "fhvhv_tripdata_2023-07_sample.parquet",
            compression="snappy",
        )
        pd.read_csv(zone_source).to_parquet(
            output_dir / "taxi_zone_lookup.parquet", index=False
        )
        pd.read_csv(weather_source, dtype=str, low_memory=False).to_parquet(
            output_dir / "weather_2023.parquet", index=False
        )

    print(f"Created three local demo files in {output_dir.resolve()}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=Path("data/local"))
    parser.add_argument("--rows", type=int, default=250_000)
    args = parser.parse_args()
    if args.rows <= 0:
        parser.error("--rows must be a positive integer")
    prepare(args.output_dir, args.rows)


if __name__ == "__main__":
    main()
